plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle:
    - error
    - { allow: ['__filename', '__dirname'] }

ignorePatterns:
  # The file is ignored because of conflicting version of jest plugin in Hexlet's linter.
  # https://github.com/jest-community/eslint-plugin-jest/blob/fb07a91b3e68546a90594023450fe85fe9fe22b5/CHANGELOG.md?plain=1#L1101
  - 'tests/errorHandling.test.js'
